export const PATH = {
    LOGIN: "/login",
    REGISTER: "/register",
    CALENDAR: "/calendar",
    HOME: "/home",
    TASKS: "/tasks",
    PROFILE: "/profile",
    FOCUS_ROOM: "/focus-room",
    SETTINGS: "/settings",
    GOOGLE_CALL_BACK: "/google/callback",
    POMODORO: "/pomodoro",
    VIDEO_CALL: "/video-call",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    IFEATUREPAGE: "*",
};
